bazel_dep(name = "rules_cc", version = "0.2.17")
bazel_dep(name = "rules_rust", version = "0.71.3")
bazel_dep(name = "aspect_rules_js", version = "3.2.3")
bazel_dep(name = "emsdk", version = "5.0.5")
bazel_dep(name = "zlib", version = "1.3.2")
bazel_dep(name = "googletest", version = "1.17.0.bcr.2", dev_dependency = True)

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2024",
    extra_target_triples = ["wasm32-unknown-emscripten"],
    rustfmt_version = "1.97.0",
    versions = ["1.97.0"],
)
use_repo(
    rust,
    "rust_toolchains",
    rust_host_tools_linux_x86_64 = "rust_linux_x86_64__x86_64-unknown-linux-gnu__stable_tools",
    rust_host_tools_macos_aarch64 = "rust_macos_aarch64__aarch64-apple-darwin__stable_tools",
)
wasm_std_repository = use_repo_rule("//tools/wasm_std:repository.bzl", "wasm_std_repository")
wasm_std_repository(
    name = "wasm_atomic_std",
    cargo_linux_x86_64 = "@rust_host_tools_linux_x86_64//:bin/cargo",
    cargo_macos_aarch64 = "@rust_host_tools_macos_aarch64//:bin/cargo",
    rustc_linux_x86_64 = "@rust_host_tools_linux_x86_64//:bin/rustc",
    rustc_macos_aarch64 = "@rust_host_tools_macos_aarch64//:bin/rustc",
)

register_toolchains(
    "//tools/wasm_std:wasm_atomic_toolchain_linux_x86_64",
    "//tools/wasm_std:wasm_atomic_toolchain_macos_aarch64",
)
register_toolchains("@rust_toolchains//:all")

npm = use_extension("@aspect_rules_js//npm:extensions.bzl", "npm")
npm.npm_translate_lock(
    name = "npm",
    custom_postinstalls = {
        "playwright-core": "PLAYWRIGHT_BROWSERS_PATH=0 node cli.js install chromium",
    },
    no_optional = True,
    pnpm_lock = "//:pnpm-lock.yaml",
)
use_repo(npm, "npm")

# Use http_archive for ImGui as it's not in BCR
http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "imgui",
    build_file = "//:third_party/imgui/imgui.BUILD",
    strip_prefix = "imgui-1.92.7-docking",
    urls = ["https://github.com/ocornut/imgui/archive/refs/tags/v1.92.7-docking.tar.gz"],
)
